version: '3'

services:
  dummywebsite:
    image: dummywebsite
    build:
      context: .
      dockerfile: dummy-website/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./monsite.dev.lan.key:/etc/nginx/ssl/monsite.dev.lan.key:ro
      - ./chaine.pem:/etc/nginx/ssl/monsite.dev.lan.pem:ro
      - ./dhparam:/etc/nginx/ssl/dhparam:ro
